version: '3.9'

services:
  bot:
    build:
      context: '.'
      dockerfile: './services/bot/Dockerfile'
    depends_on:
      - 'db'
      - 'abusive_user_checker'
      - 'prometheus'
      - 'redis'
    platform: 'linux/x86_64'
    deploy:
      restart_policy:
        condition: 'on-failure'
    pull_policy: 'build'
    environment:
      DATABASE_URL: 'postgres://prisma:prisma@db/fish?connect_timeout=3000&schema=prisma'
      REDIS_URL: 'redis://redis:6379/0'
      PORT: '9000'
      PROMETHEUS_URL: 'http://prometheus:9090'
      GRPC_CHECKER_SERVICE_URL: 'abusive_user_checker:3000'
      NODE_ENV: '${NODE_ENV:-production}'
      API_URL: '${API_URL}'
      DISCORD_TOKEN: '${DISCORD_TOKEN}'
      SHARD_COUNT: '${SHARD_COUNT}'

  abusive_user_checker:
    build:
      context: '.'
      dockerfile: './services/abusive-user-checker/Dockerfile'
    depends_on:
      - 'db'
      - 'prometheus'
    deploy:
      restart_policy:
        condition: 'on-failure'
    pull_policy: 'build'
    environment:
      DATABASE_URL: 'postgres://prisma:prisma@db/fish?sslmode=disable'
      GRPC_ADDR: ':3000'

  db:
    command: "postgres -c listen_addresses='*'"
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_USER: 'prisma'
      POSTGRES_PASSWORD: 'prisma'
      POSTGRES_DB: 'fish'
    volumes:
      - 'postgres_data:/var/lib/postgres/data'

  redis:
    image: 'redis'
    restart: 'always'
    volumes:
      - 'redis_data:/data'

  grafana:
    build: './docker/grafana'
    ports:
      - '3000:3000'
    volumes:
      - 'grafana_data:/var/lib/grafana'
    depends_on:
      - 'prometheus'
    pull_policy: 'build'

  prometheus:
    build: './docker/prometheus'
    volumes:
      - 'prometheus_data:/prometheus'
    pull_policy: 'build'

volumes:
  grafana_data:
  postgres_data:
  prometheus_data:
  redis_data:
