combine_control_expr = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 80
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
report_todo = "Never"
use_field_init_shorthand = true
wrap_comments = true
