#!/usr/bin/env bash

set -e

set -o allexport
source $(dirname $0)/../.env
set +o allexport

readarray -t domain_hashes < <(curl -sSL https://cdn.discordapp.com/bad-domains/hashes.json | jq -r '.[]')
readarray -t from_api < <(curl -sSL "$API_URL" | jq -r '.[]')

from_api_len="${#from_api[@]}"
domain_hashes_len="${#domain_hashes[@]}"

echo "discord list lentgh: $domain_hashes_len"
echo "api list length    : $from_api_len"

in_discord_list=0
not_in_discord_list=0

for domain in ${from_api[@]}; do
  hashed=$(echo -n "$domain" | shasum -a 256 | awk '{print $1}')
  if [[ " ${domain_hashes[*]} " =~ " ${hashed} " ]]; then
    in_discord_list=$((in_discord_list+1))
  else
    not_in_discord_list=$((not_in_discord_list+1))
  fi
done

echo "in discord list    : $in_discord_list"
echo "not in discord list: $not_in_discord_list"
