#!/usr/bin/env bash

root="$(dirname "$0")/.."

GO_OUT="$root/services/imgcompare"
JS_OUT="$root/services/bot/build/lib/protos"
TS_OUT="$root/services/bot/lib/protos" # idk why but this breaks if you append /protos

mkdir -p "$root/services/bot/build/lib/protos"

protoc \
  -I="$root/protos" \
  --go_out="$GO_OUT" \
  --go-grpc_out="$GO_OUT" \
  --js_out="import_style=commonjs,binary:$JS_OUT" \
  --ts_out="$TS_OUT" \
  $root/protos/*.proto
