#!/usr/bin/env bash

root="$(dirname "$0")/.."

GO_OUT="$root/services/imgcompare"
TS_OUT="$root/services/bot/lib/protos"

protoc \
  -I="$root/protos" \
  --plugin="protoc-gen-ts=$root/services/bot/node_modules/.bin/protoc-gen-ts" \
  --plugin="protoc-gen-grpc=$root/services/bot/node_modules/.bin/grpc_tools_node_protoc_plugin" \
  --go_out="$GO_OUT" \
  --go-grpc_out="$GO_OUT" \
  --grpc_out="grpc_js:$TS_OUT" \
  --js_out="import_style=commonjs,binary:$TS_OUT" \
  --ts_out="service=grpc-node,mode=grpc-js:$TS_OUT" \
  $root/protos/*.proto
