scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: '1s'

    static_configs:
      - targets: ['bot:9000']
        labels:
          service: 'fish'
          group: 'production'

      - targets: ['domain-scraper:9000']
        labels:
          service: 'domain-scraper'
          group: 'production'
