{
 "title": "Fish Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Domain Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Domain Hits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "increase(domain_gauge{}[1y])", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Domain hits per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sum(rate(domain_hits{}[1m]))" }
   ]
  },
  {
   "title": "total domains",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "domain_count{}" }
   ]
  },
  {
   "title": "known domains",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 12 },
   "targets": [
    { "expr": "domain_count{}" }
   ]
  },
  { "title": "Bot Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "total guilds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "guild_count{}" }
   ]
  },
  {
   "title": "guild count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 22 },
   "targets": [
    { "expr": "guild_count{}" }
   ]
  },
  {
   "title": "gateway ping",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(gateway_ping{}[1m])"
    }
   ]
  },
  {
   "title": "gateway ping",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "gateway_ping{}" }
   ]
  }
 ]
}